#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

#Publishing
SONATYPE_HOST=CENTRAL_PORTAL
RELEASE_SIGNING_ENABLED=true
GROUP=com.oratakashi.uangku
VERSION_NAME=0.0.1-Alpha
POM_NAME=Uangku Mobile Core
POM_DESCRIPTION=Uangku Mobile Core Library built with Kotlin Multiplatform
POM_URL=https://github.com/uangkuid/Uangku-Mobile-Core-Lib
POM_SCM_URL=https://github.com/uangkuid/Uangku-Mobile-Core-Lib
POM_SCM_CONNECTION=scm:git@github.com:uangkuid/Uangku-Mobile-Core-Lib.git
POM_SCM_DEV_CONNECTION=scm:git@github.com:uangkuid/Uangku-Mobile-Core-Lib.git
POM_LICENCE_NAME=MIT License
POM_LICENCE_URL=https://raw.githubusercontent.com/uangkuid/Uangku-Mobile-Core-Lib/main/LICENSE
POM_LICENCE_DIST=repo
POM_DEVELOPER_ID=oratakashi
POM_DEVELOPER_NAME=Oratakashi Nhamako
POM_DEVELOPER_URL=https://oratakashi.com
POM_DEVELOPER_EMAIL=oratakashi@oratakashi.com